### ISSUE TITLE
'MAC transaction expired' ,sensor freezes - LYWSD03MMC v.1,08

### ISSUE THREAD

**Issue by drwalr** [pvvx/ZigbeeTLc#10]
I reprogrammed one of my LYWSD03MMC (sensor) to version 1.08
After a few hours, the sensor stopped reporting to Z2M
The connection to the coordinator is good.

![image](https://github.com/pvvx/ZigbeeTLc/assets/90967557/86e2dfb4-db49-4747-857d-a331b4502e1d)

The sensor froze, I tried to change the ambient temperature, but the temperature and humidity did not change on the display.
Manual reading in Z2M gives an error in the 'MAC transaction expired' logs

![image](https://github.com/pvvx/ZigbeeTLc/assets/90967557/b04d0121-969b-4a7e-9ef4-06bf898ba242)

After reset, readings are normal until the next time the sensor freezes.

**Comment by pvvx** [comment]
What does the "Binding table" show from the device?

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/5f8a3961-e93b-4340-ab65-5b2e893286e4)

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/a6561068-eaba-4957-8722-42e8dfc3f704)
