### ISSUE TITLE
LYWSD03MMC HW:B1.5 doens't work with Z03MMC_v0122.bin

### ISSUE THREAD

**Issue by Dh0mp5eur** [pvvx/ZigbeeTLc#115]
Hi, 
I have some LYWSD03MMC under HA/Z2M.

Z2M suggested to upgrade the firmware to Z03MMC_v0122.bin.
After the upgrade some devices don't work.
All devices in HW B1.4 work correctly.
But those in HW B1.5 no longer display anything and no longer communicate.

Hardware:
CHMLmini_TLW_V1.5
202102
HW: B1.5

I have the same problem if I flash the firmware with the usb flasher.
I rollback to Z03MMC_v0121.bin to return to a normal state.

Thanks for your support

**Comment by pvvx** [comment]
Updated 21 hours ago with file accepted automatically to ZHA.

![image](https://github.com/user-attachments/assets/dbb1a2ae-6c8e-444b-afbe-72e1126a9924)

HW Information: HW:B1.5
![image](https://github.com/user-attachments/assets/e3136507-02b2-4bcb-aa3e-aedd2e87161d)

![image](https://github.com/user-attachments/assets/9121e548-932a-48dd-b31f-b18956b6540c)

![image](https://github.com/user-attachments/assets/ea54c7a6-d44f-413b-a556-a8eeb07fde01)

**Comment by Dh0mp5eur** [comment]
Hi,
I don't understand, after another OTA update failed.
I flashed my device via USB and now it works.

Sorry for the inconvenience.
Thanks
