### ISSUE TITLE
MHO-C122 not supported in Zigbee2MQTT

### ISSUE THREAD

**Issue by wimb0** [pvvx/ZigbeeTLc#118]
MHO-C122 seems to be missing in the zigbeetlc_v0121.js converter file.
If I understand the converter file correctly, it should show up as a LYWSD03MMC in Z2M?

I flashed one with the Zigbee firmware, and Z2m shows it as not supported:

![image](https://github.com/user-attachments/assets/87eb25a0-a91f-4925-bec4-32afe5c77d95)

**Comment by robvanoostenrijk** [comment]
Your MHO-C122 should be natively supported in Zigbee2MQTT:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/9e4c840b5466dfd0891039ddf66056fbc5e9bc9e/src/devices/zigbeetlc.ts#L121

**Comment by pvvx** [comment]
Most likely https://github.com/Koenkk does not support `manufacturerName: 'MiaoMiaoCe'`
https://www.miaomiaoce.com/

**Comment by robvanoostenrijk** [comment]
@pvvx Looks like you are correct. That is the issue here. Is this a firmware issue or MiaMiaoCe is the correct name?

@wimb0, once @pvvx confirms I'll raise a pull request against the converter in Zigbee2MQTT to rectify the manufacturer name to what the firmware is reporting.

**Comment by robvanoostenrijk** [comment]
We'll wait for pvvx to confirm if this is a firmware typo or not. If not, I'll change Zigbee2MQTT upstream.

His comment indicates it should be `MiaoMiaoCe`, as per the official website. In that case the firmware manufacturer is wrongly set (letter 'o' missing).

**Comment by juha63** [comment]
sensorEpCfg.c:

```
#define ZCL_BASIC_MFG_NAME     {9,'M','i','a','M','i','a','o','C','e'} // MiaoMiaoCe
```

This has never changed since the first commit and has always been "MiaMiaoCe". Same with MHO_C401N.

**Comment by wimb0** [comment]
Maybe fix both?
Correct name in new firmwares.
Both manufactureres in Z2M converters.

**Comment by pvvx** [comment]
Ver 0.1.2.3: Added the ability to change the "manufacturer name". Changing the structure of saving the model and the manufacturer name. Corrected manufacturer name "MiaoMiaoCe" for MHO-C122 and MHO-C401N.

**Comment by wimb0** [comment]
Thanks for the quick fix!
Will the new firmware be available as OTA in Z2M?

**Comment by pvvx** [comment]
Unfortunately I do not support or use Z2M.

**Comment by juha63** [comment]
@wimb0: You should be able to do a local OTA update in Z2M using the bin file 1141-020b-01233001-ZMHOC122.zigbee

**Comment by wimb0** [comment]
I've updated via local OTA.
My MHO-C122 is working fine now!

**Comment by wimb0** [comment]
Since this issue is resolved, I'll close it.
