### ISSUE TITLE
LYWSDCGQ/01ZM

### ISSUE THREAD

**Issue by aptem334** [pvvx/ZigbeeTLc#12]
Please add a sensor LYWSDCGQ/01ZM

**Comment by aptem334** [comment]
MJ_HT_V1

**Comment by aptem334** [comment]
![72bef3](https://github.com/pvvx/ZigbeeTLc/assets/23107015/a076581d-87d8-4872-89d9-10c9a47f5bef)
![0488af](https://github.com/pvvx/ZigbeeTLc/assets/23107015/4549cf7e-ad9a-42fb-8700-21e9f6aefc98)

**Comment by pvvx** [comment]
This is a chip from [Nordic Semiconductor](https://www.nordicsemi.com/products/nrf51802). 
Only devices based on Telink TLSR825x series chips are discussed here.

**Comment by nonflammable** [comment]
> Please add a sensor LYWSDCGQ/01ZM

Probably the nRF51802 chip does not support ZigBee

**Comment by aptem334** [comment]
Как на счет того что бы перепаять микроконтроллер из SJWS01LM? Это сработает?

**Comment by aptem334** [comment]
> This is a chip from [Nordic Semiconductor](https://www.nordicsemi.com/products/nrf51802).
> Only devices based on Telink TLSR825x series chips are discussed here.

How about resoldering the microcontroller from SJWS01LM? Will this work?

**Comment by pvvx** [comment]
Everything is possible.
Example:  https://pvvx.github.io/CGDK2/CGDK2-2/
