### ISSUE TITLE
Several LYWSD03MMC stop reporting measurements

### ISSUE THREAD

**Issue by fred777** [pvvx/ZigbeeTLc#130]
Yesterday I flashed 3 LYWSD03MMC one after the other from ATC BLE to Zigbee firmware 0x01233001 with TelinkMiFlasher.html. Integration into ZHA worked like a charm, until the morning.

The displays keep updating, but the temperatures and humidity being received by Homeassistant 2024.11.1 via ZHA are stuck since around 6am for all 3 devices and measurements are reported to have updated 6h ago.

![image](https://github.com/user-attachments/assets/16c523a9-a328-45d2-8305-70cf16fe88cf)
![image](https://github.com/user-attachments/assets/ff0ad2e6-0fb1-477e-8db1-bf5c4394f14d)

Reboot of HA didn't help.

Reconfiguring the devices fails too.

![image](https://github.com/user-attachments/assets/b1ad627f-8348-4807-8df9-0355e6224a94)

My coordinator is a SONOFF ZBDongle-E 3.0 Plus (EFR32MG21 + CH9102F/CP2102N) with firmware 7.4.3.0

What brought the devices back is a reset via battery removal:

![image](https://github.com/user-attachments/assets/e1f2a1f8-4375-489f-bb04-de8906a4f66c)

In the log it can bee seen that "a checkin event was fired" occurred every hour until 6am where it stopped. It re-appeared right after device reset.

I hope someone can help me here - I don't want to reset the thermometers every morning :see_no_evil:

**Comment by pvvx** [comment]
> Reconfiguring the devices fails too.

Bindung - Not required
Reporting - ok

---

> I hope someone can help me here - I don't want to reset the thermometers every morning

The device has nothing to do with it

When you turn the battery off and on, your Zigbee coordinator completely refreshed the "binding" and "reports".

**Comment by pvvx** [comment]
> Applying the ZHA patch seems to be affect only measurement resolution - or is there something else that I have missed?

When changing the "report" parameters, the thermometer transmits readings more often.
