### ISSUE TITLE
TS0201 (WSD500A) identifying as different device in Z2M after flashing 0.1.1.1

### ISSUE THREAD

**Issue by slingel** [pvvx/ZigbeeTLc#14]
left original, right custom firmware. help appreciated.
not receiving any data except lqi.

![tuya](https://github.com/pvvx/ZigbeeTLc/assets/7095567/211145b3-9023-4618-8cb7-de1418898a99)

**Comment by pvvx** [comment]
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/027083ab-81b0-4679-ad48-ff0981c379db)
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/b6f4ffad-da53-4eec-b98d-76079da41c82)
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/82fbeacf-ccdd-4c90-be4c-c306a2774b4a)
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/01d1cae8-2efd-4a7a-89d1-3366ec7beace)
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/877acd8e-000f-4272-8b9d-e5eb549a73e2)

**Comment by slingel** [comment]
> Your program (integration) is wrong. Write to the program creators.
> 
> What kind of manufacturer is this with the name “_TZ3000_xr3htd96”? Where did “sensor with display” come from? Where is the manufacturer's number? Where is the Zigbee version number? What has the software degenerated to - it can no longer correctly read "Attributes for determining basic information about the device"? ![image](https://user-images.githubusercontent.com/12629515/285142333-9763b2a6-0dbb-433d-8212-48b159d02fb6.png)
> 
> Cluster 0x0001: Basic ZCLVersion: 3 ApplicationVersion: 0 StackVersion: 2 HWVersion: 1 ManufacturerName: "Tuya" ModelIdentifier: "TS0201" DateCode: "20231121" PowerSource: 3 - Battery SWBuildID: "3001-0111" Cluster 0x0019: OTA Manufacturer ID: 0x1141 (Telink) or in the future there will be 0xD0E5 (DOES -> DIY) ...
> 
> ![image](https://user-images.githubusercontent.com/12629515/285130838-027083ab-81b0-4679-ad48-ff0981c379db.png) ![image](https://user-images.githubusercontent.com/12629515/285130861-b6f4ffad-da53-4eec-b98d-76079da41c82.png) ![image](https://user-images.githubusercontent.com/12629515/285130875-82fbeacf-ccdd-4c90-be4c-c306a2774b4a.png) ![image](https://user-images.githubusercontent.com/12629515/285130886-01d1cae8-2efd-4a7a-89d1-3366ec7beace.png) ![image](https://user-images.githubusercontent.com/12629515/285130899-877acd8e-000f-4272-8b9d-e5eb549a73e2.png)

**Comment by pvvx** [comment]
Because Z2M is not user friendly, use the gag from the https://github.com/devbis/z03mmc/blob/master/converters/lywsd03mmc.js

change lines:
```
    zigbeeModel: ['TS0201'],
    model: 'TS0201',
    vendor: 'Tuya',
```
Or manually binding the required measurements (clusters).

**Comment by slingel** [comment]
working fine now. ota update working too. thank you.

```const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['TS0201'],
    model: 'WSD500A',
    vendor: 'Tuya',
    description: 'Temperature & humidity sensor',
    fromZigbee: [fz.temperature, fz.humidity, fz.battery, fz.hvac_user_interface],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.temperature(endpoint, {min: 10, max: 300, change: 10});
        await reporting.humidity(endpoint, {min: 10, max: 300, change: 50});
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
    },
    exposes: [
        e.temperature(), e.humidity(), e.battery(), e.battery_voltage(),
    ],
    ota: ota.zigbeeOTA,
};

module.exports = definition;
```

![ts0201](https://github.com/pvvx/ZigbeeTLc/assets/7095567/74eaf5ae-3281-4b09-a106-c46b9e3ce254)

**Comment by khayamgondal** [comment]
@slingel I am facing the same issue. Where do I paste the code above to get it corrected? @pvvx

**Comment by slingel** [comment]
in the zigbee2mqtt data folder create a converter named ts0201.js or something like that and then add it to the bottom of configuration.yaml in the same folder like this:

```
external_converters:
  - ts0201.js
  ```
