### ISSUE TITLE
Questions regarding dumping and developing for a device based on the TLSR8258

### ISSUE THREAD

**Issue by louisprp** [pvvx/ZigbeeTLc#140]
I’ve come across this project on my search for flashing Telink based devices with custom firmware, and while my device is a button rather than a thermostat, I’ve hoped to get some guidance here on the process of developing firmware for it. The device in question is a generic Tuya Smart Knob, as found [here](https://a.aliexpress.com/_Ez0fxJE). Upon opening the device I could identify the specific chipset used, in particular the TLSR8258F512ET32. Furthermore, I could also see some pins are available on the side of the device. I believe to have identified them as being 3.3V, Pin 5 of the microcontroller, Pin 6, GND and Pin 17. Judging by the [Datasheet](http://wiki.telink-semi.cn/doc/ds/DS_TLSR8258-E_Datasheet%20for%20Telink%20BLE+IEEE802.15.4%20Multi-Standard%20Wireless%20SoC%20TLSR8258.pdf), the seem to be responsible for SWS and UART communication.

Before proceeding, I would like to dump the current firmware of the chip, such that I can restore it later to it’s original state. I’m a bit unsure however, what hardware I need for this. As I understand, Swire is a protocol established by Telink themselves, for which they offer their own programmer. I would much prefer however, to use a common CH340G based USB to TTL device to establish the connection, or perhaps other readily available hardware. I’m unsure whether it is possible to connect to the device over BLE, since it is advertised as a ZigBee device, but I’ll do more testing. 

After these steps are done, I would appreciate any resources on reverse engineering the firmware from the device and recommendations for developing custom firmware for this board. Thank you for your help and the work you’ve already done!

Here are some images as a reference
![image](https://github.com/user-attachments/assets/d91e9578-60fe-4aba-b20e-2ecf36eb74a9)
![image](https://github.com/user-attachments/assets/29098d3b-1389-4ca6-a157-afda64c014b2)
![image](https://github.com/user-attachments/assets/5202dd24-46af-4ff0-8db4-af5dd7386ac6)

**Comment by pvvx** [comment]
https://github.com/pvvx/TlsrComSwireWriter -> TLSR825xComFlasher.py
