### ISSUE TITLE
Some questions about zigbee firmware

### ISSUE THREAD

**Issue by PetrMa** [pvvx/ZigbeeTLc#16]
Hi,

at first, thank you for your hardwork. 

as I would like to test the new Zigbee firmware, I need to ask you for some details:
1) is it better to use your firmware or firmware from devbis? which one you recommend?
2) do you plan to make firmware and OTA for Z2M? If not and I´am using Z2M, it is devbis version better for me at this time?
3) is there any way how to update your firmware via Z2M manually?
4) is there any way how to migrate from your Z2M to devbis or back?

Sorry for these questions but I think I´am not only one user who is confused of these two different versions and I hope this can help other users to make decision.
Thanks, regards, Petr

**Comment by pvvx** [comment]
1. Of your choice
2. I don't use z2m. I don’t know how and what works in z2m. And I do not publish beta firmware versions in general lists for automatic updates (OTA) of Zigbee devices for all users. When everything is debugged and checked, then publication is possible.
3. Yes, it is possible to update the firmware in z2m manually.
4. Yes. This has so far been implemented only with the help of my utilities and firmware via BLE.
