### ISSUE TITLE
Offset humidity/temp 

### ISSUE THREAD

**Issue by thkrmr** [pvvx/ZigbeeTLc#18]
Is it possible to control the offset for humidity and temperature with the Zigbee firmware? With the BLE firmware I can do it directly in Telink Flasher, but obviously you can't use the Flasher anymore once the Zigbee variant is flashed. 

I wanted to control the offset on device level, not HA, so that the display on the device itself would be correct as well. I use ZHA. I have 'calibrated' values for a bunch of LYWSD03MMC, because they drift when it comes to humidity.

**Comment by pvvx** [comment]
Introduce (represent) standard cluster numbers and attributes to Zigbee to change parameters.

**Comment by pvvx** [comment]
Added to [README.md](https://github.com/pvvx/ZigbeeTLc#readme): Home Assistant with ZHA does not have functions for additional configuration of Zigbee devices. Until this changes, there can be no additions to the firmware.

**Comment by pvvx** [comment]
To get started, try:

_9. Switch temperature between Celsius and Fahrenheit (ClusterID: 0x0204, Attr: 0x0000, ENUM8 = 1 in C, = 2 in F)_

https://github.com/pvvx/ZigbeeTLc#current-additions

**Comment by pvvx** [comment]
[Added for ZHA](https://github.com/pvvx/ZigbeeTLc/issues/28) (fw ver 0.1.1.5)

**Comment by pvvx** [comment]
[ZHA: Setting offsets for temperature and humidity](https://github.com/pvvx/ZigbeeTLc/issues/30)
Available starting from firmware version 0.1.1.6.
