### ISSUE TITLE
Не обновляется в z2m по ota

### ISSUE THREAD

**Issue by Gita1985** [pvvx/ZigbeeTLc#2]
![Screenshot_20231115_214701_io homeassistant companion android minimal](https://github.com/pvvx/ZigbeeTLc/assets/109899248/60cce31c-3925-40fc-a77b-a966d31fdeaf)

**Comment by pvvx** [comment]
Что и во что не обновляется?

**Comment by Gita1985** [comment]
Прошил по вашей инструкции LYWSD03MMC в zigbee. В z2m отображается и работает, но не обновляется по OTA или так и должно быть?

**Comment by pvvx** [comment]
Во что он должен обновиться?
Я не публиковал в общие списки zigbee прошивок, пока они в Beta стадии.
Скопируйте новые файлы вручную в каталог для обновления.
Я использую ZHA.
Если какие-то сложности, то берете файлы из [zigbee_ota to ble](https://github.com/pvvx/ATC_MiThermometer/tree/master/zigbee_ota) и термометр перешивается обратно в BLE. Далее опять накатываете любую версию Zigbee, хоть со всеми новыми идентификаторами.
Одна проблема - после прошивки zigbee в ble, требуется стереть файлы fw и перезагрузить HA. 
Иначе он опять обновит всё в BLE, т.к. где-то помнит прошивки до полного перезапуска...

**Comment by Gita1985** [comment]
Ок. Спасибо! Т.е. в дальнейшем должно работать обновление? Сейчас проблем нет. Все работает

**Comment by pvvx** [comment]
В ver 0.1.0.4 [серьезные исправления](https://github.com/devbis/z03mmc/issues/47#issuecomment-1813514345) по поводу передачи измерений.

**Comment by Gita1985** [comment]
А как мне обновить? Есть инструкция обновления устройства, которое уже перешито в ZigBee? Заранее благодарю

**Comment by pvvx** [comment]
С z2m не работал.
