### ISSUE TITLE
Tuya TH05

### ISSUE THREAD

**Issue by Monacoslo** [pvvx/ZigbeeTLc#22]
Please add support to most popular Tuya TH05 sensors that are constantly on promotion on Aliexpress and look the same as xiaomi.
![PXL_20231201_125632884](https://github.com/pvvx/ZigbeeTLc/assets/47989822/39386711-e487-41af-9a50-fea954b138ef)
![PXL_20231201_124318378](https://github.com/pvvx/ZigbeeTLc/assets/47989822/ef690df9-d9c2-4df4-a2fc-d3f7a8516201)

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc/discussions/21
