### ISSUE TITLE
Не обновляются значения температуры

### ISSUE THREAD

**Issue by dailrus** [pvvx/ZigbeeTLc#26]
Подключен через Sonoff dongle и zha.
На экране термометра изменяются показания температуры и влажности, но в ХА изменяются только значения влажности. (изменение на 0.4 градуса, прошло больше 2 минут)
Если правильно понял, интервал обновления не реже 1 раза в 2 минуты?

**Comment by pvvx** [comment]
Default значения, записанные в самом термометре: 
Температура:  минимум 30 сек, максимум 120 сек, дельта изменения 0.1 С
Влажность:  минимум 30 сек, максимум 120 сек, дельта изменения 0.5 %

ZHA устанавливает свои значения, ужасные - так нравится писателям ZHA.
Для изменения требуется [патч ZHA](https://github.com/pvvx/ZigbeeTLc/issues/6). Других способов в HA не дано.
