### ISSUE TITLE
[Request] add OTA firmware on Zigbee2MQTT

### ISSUE THREAD

**Issue by nonflammable** [pvvx/ZigbeeTLc#3]
Add OTA firmware on Zigbee2MQTT & option (or tutorial) to change firmware from z03mmc to ZigbeeTLc
BTW ... what are the differences between these firmwares ?

**Comment by pvvx** [comment]
> Add OTA firmware on Z2M & option (or tutorial) to change firmware from z03mmc to ZigbeeTLc

I don't use z2m.

> what are the differences between these firmwares ?

Main differences:
1. Battery consumption has been reduced by more than 1.5 times.
2. Fixed sending reports. In the devbis version, only one report is sent if others are active.

**Comment by nonflammable** [comment]
Flashed back from devbis version (via USB) 😇 
Now I'm waiting for MHO-C401(old) version 😄

**Comment by pvvx** [comment]
> Flashed back from devbis version (via USB)

Without wires:
[1141-0203-99993001-ATC_v46.zigbee](https://github.com/pvvx/ATC_MiThermometer/blob/master/zigbee_ota/1141-0203-99993001-ATC_v46.zigbee) -> [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) -> All Zigbee

**Comment by pvvx** [comment]
> Now I'm waiting for MHO-C401(old) version 

It will be long enough.
This model updates the display very slowly and requires a lot of battery power. Requires long-term maintenance of the display controller while other tasks (Zigbee stack) are running.
