### ISSUE TITLE
The battery level does not update

### ISSUE THREAD

**Issue by ivankravets** [pvvx/ZigbeeTLc#39]
I'm experimenting with Zigbee and this firmware for LYWSD03MMC device. It works great for me. However, the battery stays at 3.2V and 100% for 2 days. I'm sure this is not true as the voltage is lower.

Is it possible to enable real-time voltage measurement?

<img width="562" alt="Screenshot 2023-12-28 at 11 59 55" src="https://github.com/pvvx/ZigbeeTLc/assets/1760209/e6e93d0d-1bfd-4718-adb1-26c82b3450f7">

**Comment by pvvx** [comment]
Change the minimum and maximum reporting interval parameters for battery cluster.

A battery charge percentage of 0..100% corresponds to a voltage of 2.2..3.0 V.

**Comment by ivankravets** [comment]
Thanks for the help!
