### ISSUE TITLE
LYWSD03MMC schematic

### ISSUE THREAD

**Issue by tovy14** [pvvx/ZigbeeTLc#74]
Hi,
After flashing the 1st sensor, i thought i would do them all, boy i was wrong. I managed to rip the P14 pad off the board while soldering.

Does someone have a schematic for where the P14 pad is connected to on the board?

Thank you.

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/tree/master/BoardPinout

P14 -> SWS ->  pin N4 TLSR8251F512ET24

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/844affca-ab63-4e43-b475-bb38e8b73b32)

**Comment by tovy14** [comment]
> https://github.com/pvvx/ATC_MiThermometer/tree/master/BoardPinout
> 
> P14 -> SWS -> pin N4 TLSR8251F512ET24
> 
> ![image](https://private-user-images.githubusercontent.com/12629515/313194633-844affca-ab63-4e43-b475-bb38e8b73b32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDcwMjMsIm5iZiI6MTcxMDUwNjcyMywicGF0aCI6Ii8xMjYyOTUxNS8zMTMxOTQ2MzMtODQ0YWZmY2EtYWI2My00ZTQzLWI0NzUtYmIzOGU4YjczYjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEyNDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzYyYmVkZjMyMzE3MzVjMmE4OTBjMTllZjY2YjlmNWVjMjJlYTc3OWJhMzBhMzc1ZjExMzVkYWI0NTJlNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ln9BttMt4n7PC0jw0lE-uWq6X5_1fFHUG6f3Ga8V34c)

Thank you very much, sorry still kind of new top Github, will check better next time!
