### ISSUE TITLE
Can't connect Qingping Temp RH Lite to HomeAssistant

### ISSUE THREAD

**Issue by muscaiu** [pvvx/ZigbeeTLc#78]
I'm trying to add Qingping Temp RH Lite to HomeAssistant by flashing it with Telink Flasher, but it gets stuck on this step "Activating now, please wait..."

<img width="1680" alt="Screenshot 2024-03-26 at 14 19 45" src="https://github.com/pvvx/ZigbeeTLc/assets/11426309/d773d537-8a70-4cd0-84f7-52b7a421b718">

I have other Xiaomi devices added with this method, but no luck with this first QingPing device i just bought.

<img width="955" alt="Screenshot 2024-03-26 at 14 27 53" src="https://github.com/pvvx/ZigbeeTLc/assets/11426309/963ca91e-e1cb-4b0c-981f-d35fedd9b7f6">

Need to mention i don't have a Xiaomi hub, i'm using USB dongle attached to RPi.    
Any suggestion?

**Comment by robvanoostenrijk** [comment]
You need to press the button on the back of the Qingping while doing the activation.
If you get the timing right, it will go through eventually.

**Comment by muscaiu** [comment]
I just realized it works if you keep the back button pressed for 5 seconds. /facepalm.
Closing
