### ISSUE TITLE
CGDK2: Missing ZigBee Cluster

### ISSUE THREAD

**Issue by robvanoostenrijk** [pvvx/ZigbeeTLc#82]
When using multiple CGDK2 devices, I found an interesting issue.

All of the devices are paired with Z2M and report their statistics successfully. 

However, one of the devices fails to report a `hvacUserInterfaceCfg` input cluster.

**Device with the issue:**
<img width="312" alt="image" src="https://github.com/pvvx/ZigbeeTLc/assets/6480052/9a3945b3-cacc-4265-a14a-f98924ebf760">

<img width="697" alt="image" src="https://github.com/pvvx/ZigbeeTLc/assets/6480052/f3a7ff9b-12b7-445e-bdbc-514ae933cbda">

**Device working normally:**
<img width="306" alt="image" src="https://github.com/pvvx/ZigbeeTLc/assets/6480052/bad300ed-acd8-425e-ac36-56343556ed58">

<img width="675" alt="image" src="https://github.com/pvvx/ZigbeeTLc/assets/6480052/7f30a0da-53b5-46cc-bd12-d563543a0962">

Firmware on both devices was updated through OTA successfully and is identical. 
I've tried to remove & repair and reconfigure the problematic device, but it keeps reporting these exact clusters.

Any idea why this could be the case? Is there some configuration on the device itself which is causing the firmware to report different clusters?

Is there any way to reset the device local config / data, I assume this requires going to BLE firmware and back?

**Comment by pvvx** [comment]
Definition for Incoming clusters:
https://github.com/pvvx/ZigbeeTLc/blob/master/src/sensorEpCfg.c#L67

ZCL_CLUSTER_HAVC_USER_INTERFACE_CONFIG is defined only in outClusterList:
https://github.com/pvvx/ZigbeeTLc/blob/master/src/sensorEpCfg.c#L89

**Comment by robvanoostenrijk** [comment]
Thanks, I'll adjust the Z2M convertors to follow the in/out cluster definition as per source code.

**Comment by pvvx** [comment]
In the next version of HAVC USER_INTERFACE will be moved to "input clusters".
Previously, only when HAVC USER_INTERFACE was in the "output clusters" list did third-party software work correctly. Now it's fixed and needs to be done correctly.
