### ISSUE TITLE
OTA update in Z2M

### ISSUE THREAD

**Issue by PetrMa** [pvvx/ZigbeeTLc#9]
Hello,

I made a flash of my BT thermometer to Zigbee with your flasher on https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
Now I´am on version:
20231108
3001-0101
![image](https://github.com/pvvx/ZigbeeTLc/assets/24729480/0247215e-dd1f-4056-afb1-fb596b187c90)

Is there any way how to make an OTA update to latest version in Z2M please?
I tried to download this file https://github.com/pvvx/ZigbeeTLc/blob/master/bin/1141-020a-01103001-Z03MMC.zigbee and make manual OTA in Z2M but it ends all time with an error:
![image](https://github.com/pvvx/ZigbeeTLc/assets/24729480/e1f22a67-7dbb-40c2-8c6a-d2ba2d5fa987)

Thanks for your help

**Comment by nonflammable** [comment]
You should download this file:
https://github.com/pvvx/ZigbeeTLc/raw/master/bin/1141-020a-01103001-Z03MMC.zigbee
size: 126274

**Comment by PetrMa** [comment]
@nonflammable I have the correct zigbee file but it ends wit the same error message

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc/issues/11#issuecomment-1819878948

**Comment by PetrMa** [comment]
@pvvx OK, so the USB UART is the only one way at this time, right?

**Comment by pvvx** [comment]
Yes
