### ISSUE TITLE
Temperature not updating, but humidity does

### ISSUE THREAD

**Issue by luvxinh** [pvvx/ZigbeeTLc#98]
![Screenshot_20240529_194043_Home Assistant.jpg](https://github.com/pvvx/ZigbeeTLc/assets/33537323/7c15e8d7-ddc5-449f-9157-09a6b097a671)

![Screenshot_20240529_200659_Home Assistant.jpg](https://github.com/pvvx/ZigbeeTLc/assets/33537323/c9e67831-f12a-4b1f-ae1b-dc741824e3cc)

![Screenshot_20240529_194037_Home Assistant.jpg](https://github.com/pvvx/ZigbeeTLc/assets/33537323/be2d8281-0dd0-4c91-8d08-3ec78fcd9c29)

So in my case, the humidity reading is updated fine but the temperature reading does not update, unless I go into Manage zigbee device and force update, then it would have the new reading but then again, no update from then.

**Comment by pvvx** [comment]
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/60d2ac82-e2b1-4aa8-84ec-2fec1cc23554)

**Comment by luvxinh** [comment]
I got this.
![image](https://github.com/pvvx/ZigbeeTLc/assets/33537323/f4117811-3dbe-48da-bfec-7a08962db2ef)

Also this is in the log.

Logger: homeassistant.components.zha.core.cluster_handlers
Source: components/zha/core/cluster_handlers/__init__.py:560
integration: Zigbee Home Automation (documentation, issues)
First occurred: 11:54:58 (2 occurrences)
Last logged: 11:54:58

[0xAF30:2:0x0300]: [Min mireds is 0, setting to 153] Please open an issue on the quirks repo to have this device corrected

I hope this can be of help

**Comment by pvvx** [comment]
>  [Min mireds is 0, setting to 153] Please open an issue on the quirks repo to have this device corrected

I don't have such a message.
The coordinator on EFR32MG21 is used.
![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/cbe6ddca-704d-409d-8bb3-5a61e6492d1a)

**Comment by luvxinh** [comment]
I'm marking this as closed because after some time, the sensor ... updates. Frequency wise, it's haywire though ...

Still I appreciate the zigbee patch

**Comment by luvxinh** [comment]
Hi

Just want to clear the confusion for anyone reading ... it was **not** because the sensor did not update, but rather the temperature did not change for more than 0.5 degree celcius ... took my awhile to realize that.

Thanks for the firmware.

**Comment by pvvx** [comment]
If there has been no change for 0.5C (1%), ZHA sets the update time to 900 seconds by default.
