### ISSUE TITLE
lywsd03mmc 'UNSUPPORTED_ATTRIBUTE' when enable_display

### ISSUE THREAD

**Issue by drwalr** [pvvx/ZigbeeTLc#99]
I have 'UNSUPPORTED_ATTRIBUTE' when enable_display in  lywsd03mmc sensor.

![image](https://github.com/pvvx/ZigbeeTLc/assets/90967557/5536184c-129c-4182-8d6c-6c2aa062bf93)

firmware Ver 0.1.2.1 , Z2M 1.37.1

**Comment by pvvx** [comment]
[zigbeetlc_v0121.js](https://github.com/pvvx/ZigbeeTLc/blob/master/z2m/zigbeetlc_v0121.js)
